/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TriviaGeografia;

import LogicaGuardar.GuardarPuntos;
import LogicaGuardar.Puntos;
import LogicaGuardar.TriviaGeografia;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author malol
 */
public class Pregunta18 extends javax.swing.JFrame {
private ArrayList<TriviaGeografia> arr=new ArrayList<>();
    public String usuario;
    int puntos=0;
    int lugar;
    int nivel=0;
    ArrayList<Puntos> arr2=null;
    GuardarPuntos gp=new GuardarPuntos();
    public Pregunta18() {
        initComponents();
        lugar=0;
        
        arr2=new ArrayList<Puntos>();
        arr2=gp.getLectura("Puntos.txt");
        
        this.usuario=usuario;
        
        for(int i=0;i<arr.size();i++){
            if(usuario.equals(arr2.get(i).getnombrejugador()) && "TriviaGeografia".equals(arr2.get(i).getnombrejuego())){// EN CADA JUEGO CAMBIAN EL NOMBRE DEL JUEGO DONDE DICE Tetris
                puntos=arr2.get(i).getpuntos();
                nivel=arr2.get(i).getnivel();
                lugar=i;
                
                i=arr.size();
            }
    }
      if(lugar==-1){
            Puntos pu=new Puntos("TriviaGeografia",usuario,0,1);// AQUI TAMBIEN CAMBIEN EL NOMBRE DEL JUEGO
            arr2.add(pu);
            lugar=arr2.lastIndexOf(pu);
            JOptionPane.showMessageDialog(rootPane, "Primera vez que juega, puntaje 0");
        }else JOptionPane.showMessageDialog(rootPane, "Bienvenido "+arr2.get(lugar).getnombrejugador()+". Su puntaje en el Trivia Geografia es "+arr2.get(lugar).getpuntos());
        
        

        arr.add(new TriviaGeografia("¿Cuál es la capital de Ecuador? ",2,"Lima","Quito","Bogotá"));
//        18
        arr.add(new TriviaGeografia("¿Cuál de estos paises no está en una isla? ",2,"Madagascar","Ghana","Japón"));
//        19
        arr.add(new TriviaGeografia("¿Donde vivía Pablo Escobar? ",1,"Colombia","España","Chie"));
//        20
        this.Pregunta18.setText(arr.get(nivel).getpregunta());
        boton1.setText(arr.get(nivel).getr1());
        boton2.setText(arr.get(nivel).getr2());
        boton3.setText(arr.get(nivel).getr3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pregunta18 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("GEOGRAFÍA");

        Pregunta18.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        Pregunta18.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta18.setText("¿Cuál es la capital de Ecuador?  ");

        boton1.setBackground(new java.awt.Color(51, 102, 255));
        boton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setText("Lima");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(51, 102, 255));
        boton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setText("Quito");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setBackground(new java.awt.Color(51, 102, 255));
        boton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton3.setForeground(new java.awt.Color(255, 255, 255));
        boton3.setText("Bogotá");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Pregunta18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(Pregunta18)
                .addGap(27, 27, 27)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
if(arr.get(lugar).getresp()==1){
            
            JOptionPane.showMessageDialog(rootPane, "¡CORRECTO!, AVANZAS.");
            
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }else{
            JOptionPane.showMessageDialog(rootPane, "¡INCORRECTO!, NO AVANZAS.");
            
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }// TODO add your handling code here:// TODO add your handli        //      // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
if(arr.get(lugar).getresp()==2){
            JOptionPane.showMessageDialog(rootPane, "CORRECTO, AVANZAS.");
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }else{
            JOptionPane.showMessageDialog(rootPane, "¡INCORRECTO!, NO AVANZAS.");
            
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }    // TODO add your handling code here:////// T      // TODO add your hand         // TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
if(arr.get(lugar).getresp()==3){
            JOptionPane.showMessageDialog(rootPane, "CORRECTO, AVANZAS.");
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }else{
            JOptionPane.showMessageDialog(rootPane, "¡INCORRECTO!, NO AVANZAS.");
            
            lugar++;
            this.Pregunta18.setText(arr.get(lugar).getpregunta());
            boton1.setText(arr.get(lugar).getr1());
            boton2.setText(arr.get(lugar).getr2());
            boton3.setText(arr.get(lugar).getr3());
        }// TODO add your handling code here:   // TODO      //  /     // TODO add your han       // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta18().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pregunta18;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
